import React from 'react';

function About() {
  return (
    <div className="container mx-auto p-6">
      <h1 className="text-3xl font-bold mb-4">About Footsteps Power Generator</h1>
      <p className="text-lg mb-4">
        Welcome to <strong>Footsteps Power Generator</strong>, a groundbreaking initiative that harnesses the power of every step you take. Our mission is to provide innovative, sustainable energy solutions through the most natural movement—your footsteps. We believe in making energy generation accessible, environmentally friendly, and simple for everyone.
      </p>
      
      <h2 className="text-2xl font-semibold mb-2">Our Mission</h2>
      <p className="text-lg mb-4">
        At Footsteps Power Generator, our mission is to harness human motion and turn it into clean, renewable energy. We aim to revolutionize the way we think about energy consumption by making everyday activities part of the solution. Every step counts, and through our advanced technology, we aim to power homes, businesses, and more, all from the energy generated by the footsteps of individuals walking.
      </p>
      
      <h2 className="text-2xl font-semibold mb-2">How It Works</h2>
      <p className="text-lg mb-4">
        Our technology is based on piezoelectric systems, which capture the mechanical energy from footsteps and convert it into electrical energy. By installing these systems in high-foot-traffic areas such as streets, malls, and public buildings, we can efficiently collect energy that would otherwise go to waste. This clean energy can be used to power various devices, lights, and even contribute to the grid. 
      </p>

      <h2 className="text-2xl font-semibold mb-2">Why Choose Us?</h2>
      <ul className="list-disc pl-6 mb-4">
        <li className="text-lg">Sustainable energy source: By converting everyday movements into power, we contribute to a greener planet.</li>
        <li className="text-lg">Cost-effective: Our technology helps reduce energy costs for businesses and municipalities.</li>
        <li className="text-lg">Scalable: From small installations to large-scale energy systems, our solution can grow with your needs.</li>
        <li className="text-lg">Innovative: We are pioneers in the field of energy generation from human motion, constantly pushing the boundaries of what's possible.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-2">Join Us in Changing the World</h2>
      <p className="text-lg mb-4">
        Footsteps Power Generator is more than just a product; it's a movement. Together, we can make every step count towards a more sustainable future. Whether you're a business looking to reduce energy costs, or an individual interested in innovative energy solutions, we invite you to explore the possibilities with us.
      </p>

      <p className="text-lg mb-4">
        Learn more about how we can help you generate power from your steps. <a href="/contact" className="text-blue-500">Contact us</a> today to get started.
      </p>
    </div>
  );
}

export default About;
